apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-prod-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: todo-prod-env
  source:
    repoURL: https://github.com/CloudNativeEntrepreneur/todo-prod-env
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-prod-env
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true